# Generated by Django 5.1.6 on 2025-02-26 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_version', models.CharField(auto_created=True, default='A', editable=False, max_length=2)),
                ('tracking_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('proposal_id', models.CharField(max_length=200, verbose_name='Código da Proposta')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('contribution_margin', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Margem de Contribuição(%)')),
                ('vendor_comission', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Comissão de Venda(%)')),
                ('state', models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo')], max_length=200, verbose_name='Estado da Venda')),
                ('difal_check', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Difal?')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(choices=[('TAV', 'Tanque Vertical p/ Armazenamento'), ('TA', 'Tanque Agitador'), ('VP', 'Vaso de Pressão')], verbose_name='Tipo do Produto')),
                ('product_model', models.IntegerField(choices=[('FPTE', 'Fundo Plano/Tampo Elíptico'), ('FPTP', 'Fundo Plano/Tampo Plano'), ('FETE', 'Fundo Elíptico/Tampo Elíptico')], verbose_name='Tipo do Produto')),
                ('diameter', models.IntegerField(choices=[(1000, '1000 mm'), (2500, '2500 mm')], verbose_name='Diâmetro Interno')),
                ('cylindrical_length', models.IntegerField(verbose_name='Comprimento Cilíndrico')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='create_quotations.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
