# Generated by Django 5.1.6 on 2025-02-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='product_model',
            field=models.CharField(choices=[('FPTE', 'Fundo Plano/Tampo Elíptico'), ('FPTP', 'Fundo Plano/Tampo Plano'), ('FETE', 'Fundo Elíptico/Tampo Elíptico')], max_length=200, verbose_name='Tipo do Produto'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='product_type',
            field=models.CharField(choices=[('TAV', 'Tanque Vertical p/ Armazenamento'), ('TA', 'Tanque Agitador'), ('VP', 'Vaso de Pressão')], max_length=200, verbose_name='Tipo do Produto'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='create_quotations.quotation'),
        ),
    ]
