# Generated by Django 5.1.6 on 2025-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_quotations', '0002_alter_tank_product_model_alter_tank_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
